name: 'Approved Commit Action'
description: 'Wait for approval from a repository maintainer on a workflow run'
author: 'Balena <hello@balena.io>'

inputs:
  github-token:
    description:
      'GitHub token for authentication. The user associated with this token is
      not eligible to review.'
    required: false
    default: ${{ github.token }}
  poll-interval:
    description: 'Interval in seconds between checks for reactions.'
    required: false
    default: '10'
  allow-authors:
    description:
      'Allow pull request commit authors to approve or reject the workflow.'
    required: false
    default: 'false'

outputs:
  comment-id:
    description: 'ID of the comment requiring review.'
  approved-by:
    description: 'Username of the user who approved the workflow run.'
  rejected-by:
    description: 'Username of the user who rejected the workflow run.'

runs:
  using: 'node20'
  main: dist/index.js
  post: dist/index.js
  post-if: 'always()'
