name: 'Approved Commit Action'
description:
  'Check for approval from a repository maintainer via pull request reviews'
author: 'Balena <hello@balena.io>'

inputs:
  github-token:
    description:
      'GitHub token for authentication. Requires `pull-requests: write`
      permission.'
    required: false
    default: ${{ github.token }}
  allow-authors:
    description:
      'Allow pull request commit authors to approve or reject the workflow.'
    required: false
    default: 'false'

outputs:
  approved-by:
    description: 'Username of the user who approved the workflow run.'
  review-id:
    description: 'ID of the review that approved the workflow run.'
  review-type:
    description: 'Type of approval found (approval or comment).'

runs:
  using: 'node20'
  main: dist/index.js
  post: dist/index.js
  post-if: 'always()'
